### ISSUE TITLE
Lint keeps showing a message even with the the problem solved

### ISSUE THREAD

**Issue by gerep** [fatih/vim-go#1186]
### Behaviour

Not commenting an exported variable/function will make lint alert:

> comment on exported const InvalidBranch should be of the form "InvalidBranch ..."

### Steps to reproduce:

1. Create an exported variable and save the file, the linter will alert about the missing comment.
2. Add the comment and save, the linter will still alert about the missing comment.

### Configuration
* vimrc:

```
execute pathogen#infect()
filetype plugin indent on

autocmd BufWritePost,FileWritePost *.go execute 'GoImports' | cwindow
autocmd BufWritePost,FileWritePost *.go execute 'GoLint' | cwindow
```

* vim -version: `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 22:32:42)`
* vim-go version: `v1.11`
* go version: `go version go1.7.3 linux/amd64`

Here is a print of the problem:

![vim-go-bug](https://cloud.githubusercontent.com/assets/181501/22305848/2b8d0124-e324-11e6-9f18-5248a287cb38.png)

Closing and opening vim solve the problem.

**Comment by alercah** [comment]
I'm seeing this as well.

A better workaround is simply to move to the window and :q it.

**Comment by fatih** [comment]
We have already auto save and auto lint settings. Please check the documentation on how to enable them. Can you please test it  (on the latest master) and let me know what the latest state is?

**Comment by alercah** [comment]
Tried, and discovered #1305. This is still extant, however. Steps to reproduce:

1. Do not have autolint on.
2. Create a file with a lint error.
3. Run `:GoLint <cwd>` (cwd is a workaround for #1305).
4. An error message pops up with the lint error.
5. Fix the error and save.
6. Run the `GoLint` command again.
7. Observe that the error window is still there.

**Comment by gerep** [comment]
@fatih  I have updated my `.vimrc` to use the settings as you suggested and the problem was solved.

```
let g:go_fmt_autosave = 1
let g:go_metalinter_autosave = 1
```
Thanks

**Comment by alercah** [comment]
It's still not working without autosave, so this is still a bug.
