### ISSUE TITLE
go_gopls_enabled = 0 removes errors when saving

### ISSUE THREAD

**Issue by abenz1267** [fatih/vim-go#3264]
Hello,

setting `let g:go_gopls_enabled = 0` causes errors reported by gopls (via native nvim lsp + lspconfig) to disappear when saving.

Minimal config with
```
lua << EOF
require'lspconfig'.gopls.setup{}
EOF
let g:go_gopls_enabled = 0
```

Only nvim-lspconfig and vim-go installed.

This is ofc undesired behaviour.

Regards

**Comment by bhcleek** [comment]
What errors do you mean? How are they being shown to you?

It's difficult to know what could be the problem without the information that the issue template prompted you for; please consider closing this and opening a new issue that provides that info.

**Comment by abenz1267** [comment]
I mean errors in the code being reported by gopls. See here: https://drive.google.com/file/d/1QYZuTRemGnMsFFtV1klxv9UntBMSvTkN/view?usp=sharing

I just recorded this with my default nvim setup, but as i stated in the OP you can easily reproduce this with a minimal config as well. Just need: nvim (stable or nightly, i tested both), gopls (latest), go (latest), vim-go (latest), nvim-lspconfig (latest).

As you can see the error being reported by gopls just gets removed, once i save the file. This doesn't happen with `let g:go_gopls_enabled = 1`

Regards

**Comment by bhcleek** [comment]
I can't see that shared document.

**Comment by abenz1267** [comment]
My bad, forgot to adjust visibility. should work now

**Comment by bhcleek** [comment]
I'm still not sure what errors you're referring to. Do you mean the `E` in the gutter on the left?

**Comment by bhcleek** [comment]
Can you try disabling the `g:go_fmt_autosave` and `g:go_imports_autosave`? I suspect that may resolve the problem you're seeing.

I'm curious why you want to disable `gopls` integration, especially if you're already using `gopls` with the native Neovim lsp and lspconfig. FWIW, you can cause the `gopls` instance to be shared by multiple clients and plugins by starting `gopls` with its `-remote=auto` flag. Vim-go already uses that flag by default; if you'll configure `lspconfig` and Neovim's native lsp to also use the `-remote=auto` flag, then they'll all share the same server instance of `gopls`.

**Comment by abenz1267** [comment]
`g:go_imports_autosave = 0` solved the issue.

**Comment by mrsafalpiya** [comment]
I noticed when we have `let g:go_gopls_enabled = 0` and have something in the import statement to add, when we save, the required package gets imported and the diagnostics error doesn't disappear.

But as soon as we have no package to import, and we save the file, then the diagnostics error disappear.

Disabling `g:go_fmt_autosave` and `g:go_imports_autosave` solves the problem when we save the file but as soon as we run `:GoFmt`, the same problem occurs.
