### ISSUE TITLE
:GoInstall error navigation seems broken

### ISSUE THREAD

**Issue by daaku** [fatih/vim-go#404]
Haven't figure out what exactly is happening, but this was working fine until I upgraded yesterday. Steps to reproduce:

1. Start vim in a say `$HOME`
1. Open in go file say `$HOME/go/src/foo/foo.go`
1. `:GoInstall foo/..`
1. If there is a error from the `GoInstall` in `$HOME/go/src/bar/bar.go` you'll see it listed but won't be opened as it used to be.

**Comment by fatih** [comment]
Hi @daaku. Weird thing indeed. The thing is there is no code that changed `:GoInstall` since the previous release. If there is any error, `:GoInstall` calls `cwindow` which opens the quick fix list and shows all errors. It doesn't jump to it though, you need to call `:cc`. In your case, you want to jump to it, just like `:GoBuild` right ?

**Comment by daaku** [comment]
It's getting the absolute paths wrong, `:cc` doesn't work either. `:GoBuild` does in fact get them right.

**Comment by fatih** [comment]
It's so hard to test this without a proper test files. I've tried in my current GOPATH with several other packages, and in all of them it was working. Is there a way you could paste me a self contained go code so I could directly reproduce it ?

**Comment by fatih** [comment]
I also wonder if this is due: https://github.com/fatih/vim-go/commit/0d1e8c945481128ec7e17b51780a85af5046224d But again there is no way I can test it. Pinging @mattn may be he has some idea. I couldn't reproduce it (waiting for your example files)

**Comment by mattn** [comment]
I'll look into it later

**Comment by fatih** [comment]
@daaku can you test with https://github.com/fatih/vim-go/pull/405 please ?

**Comment by daaku** [comment]
I pulled but it still fails for me :/ Here's a repro case:

```sh
# setup a test case
export GOPATH=$PWD/tmp
mkdir -p $GOPATH/src/foo
mkdir -p $GOPATH/src/bar
cat << 'EOF' > $GOPATH/src/foo/foo.go
package foo

import "fmt"

func Do() {
  fmt.Println("hello from foo")
}
EOF
cat << 'EOF' > $GOPATH/src/bar/bar.go
package main

import (
  "fmt"
  "foo"
)

func main() {
  foo.Do()
  fmt.Println("hello from bar")
}
EOF
go install -v ...
$GOPATH/bin/bar

# now break the code so go install fails
cat << 'EOF' > $GOPATH/src/foo/foo.go
package foo

func Do() {
  fmt.Println("hello from foo")
}
EOF
go install -v ...

# open this and run :GoInstall
vim $GOPATH/src/bar/bar.go
```

**Comment by fatih** [comment]
Thanks @daaku. Will look at it in the morning.

**Comment by fatih** [comment]
Thanks @daaku I can now reproduce it. I've fixed it with https://github.com/fatih/vim-go/pull/410. Can you please try it? Now it successfully parses the error location and put's into the quickfix list. Note that `:GoInstall` doesn't have an autojump to error like the others (just noticed it). So you need to call manually `:cc`. That is also fixed with the PR: https://github.com/fatih/vim-go/pull/411. Please let me know how it works for you, I've really tried to cover all cases this time.

**Comment by daaku** [comment]
Really appreciate the effort @fatih! The path logic still isn't working -- it's getting the current filename, but not the directory.

**Comment by fatih** [comment]
It will show the file name but if you call `:cc` you should go the correct definition. Do you mean it should show the full path rather the file name? Or do I miss something?

**Comment by fatih** [comment]
Here is a screenshot of the fixed version of your code:

![image](https://cloud.githubusercontent.com/assets/438920/7445418/ec621946-f1ba-11e4-813d-dfec7c1f14c4.png)

**Comment by daaku** [comment]
I'm not getting the same behavior. I setup a stripped vimrc to make sure there isn't anything interfering which looks like this:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
```

(I'm using https://github.com/junegunn/vim-plug but I don't think that should matter.)

The vim-go I'm using is at rev 22544ec.

When I run `:GoInstall` my quickfix shows:

```
/home/me/src/go/src/bar/foo.go|4| undefined: fmt
```

So it's getting the `foo.go` and the line/error correct, but the directory is `bar` instead of `foo` presumably because I ran `:GoInstall` while editing a file in the `bar` directory. The rest of the instructions for the repro are the same as before.

**Comment by fatih** [comment]
This time I really couldn't reproduce it :/ With the fix at #410 it works perfect. I've also tried with the your simple vimrc. Here is a screencast showing it: http://quick.as/4ovsbqqm

I'm merging #410. Please pull master again. I think it's because you didn't try with #410 may be?

**Comment by daaku** [comment]
It's fixed! Thank you very much @fatih!

**Comment by fatih** [comment]
Finally :+1:  :)
