### ISSUE TITLE
GoTestFunc produces invalid locations when invoked on a sub package test file

### ISSUE THREAD

**Issue by ironcladlou** [fatih/vim-go#674]
As of 99a3a5fec048f0dc8ef65d292e905579b7bcbf73, running `GoTestFunc` on a test function in a sub package always produces invalid quickfix locations and an error like "Dropped [...] from location list (nonvalid filename)".

The test file is in `$GOPATH/package/a/b/foo_test.go`, and the error reports that the location from the test failure is in `$GOPATH/package/foo_test.go`.

I don't have time right now to set up a reproducable test, but it's the same underlying issue reported in #651. Reverting to 5573e9c fixes the problem.

**Comment by fatih** [comment]
Hi @ironcladlou This is fixed with: https://github.com/fatih/vim-go/pull/677 can you test it please ?

**Comment by ironcladlou** [comment]
@fatih 

I've tested with 5573e9c5f0b75bdb2b914ad33e63e153a9b6a5ff and I'm still seeing the bug but with slightly different output: Now, in addition to "Dropped [...] from location list (nonvalid filename)" I also see the output of `go test` which wasn't present before. It looks like:

```console
vim-go: [run] Dropped "/tmp/go/src/github.com/openshift/origin/controller_test.go" from location list (nonvalid filename)vim-go: --- FAIL: TestHandleScenarios (0.00s)
        controller_test.go:34: test
FAIL
exit status 1
FAIL    github.com/openshift/origin/pkg/deploy/controller/deploymentconfig      0.015s
vim-go: [test] FAIL
````

Reverting to 5573e9c5f0b75bdb2b914ad33e63e153a9b6a5ff continues to fix the problem.

**Comment by fatih** [comment]
Can you please provide a test case (example code that compiles). If I can reproduce it I can try to fix it.

**Comment by ironcladlou** [comment]
@fatih 
>Can you please provide a test case (example code that compiles). If I can reproduce it I can try to fix it.

Sure.

```console
$ tree
.
└── a
    └── a_test.go

1 directory, 1 file

$ cat a/a_test.go 
package a

import "testing"

func TestGoTestFunc(t *testing.T) {
        t.Fatal("test")
}

$ cat ~/.vimrc 
execute pathogen#infect()
syntax on
filetype plugin indent on

set tabstop=2

$ ls ~/.vim/bundle/
ctrlp  vim-go
```

Output of `GoTestFunc` from `a_test.go:6:2`:

```console
vim-go: [run] Dropped "/vagrant/gotestfunc/a_test.go" from location list (nonvalid filename)vim-go: --- FAIL: TestGoTestFunc (0.00s)                          
        a_test.go:6: test
FAIL
exit status 1
FAIL    _/vagrant/gotestfunc/a  0.002s
vim-go: [test] FAIL
```

**Comment by fatih** [comment]
Thanks @ironcladlou  for the example case. I've could reproduce it and fixed it successfully. I've pushed it to master. Please reopen and provide the most recent failure if it doesn't work for you. Thank you again for your feedback.

**Comment by ironcladlou** [comment]
Sorry for the delayed response. I verified the fix. Thanks again!

**Comment by nothingelsematters7** [comment]
For me the same problem is reproducible with :GoVet now. Should I open new issue for that?
