### ISSUE TITLE
Unabled to get completion when pressing <C-x> and <C-o>

### ISSUE THREAD

**Issue by Marneus68** [fatih/vim-go#837]
### Actual Behavior

Whlile trying to get completion working on vim using vim-go I get the following outputs when entering <C-x> and <C-o> :

`-- (insert) --`

`-- ^X mode (^J^D^E^F^I^K^L^N^O^Ps^U^V^Y)`

Unlike in the demonstration videos and gifs, I see no contextual completion window popping up.

### Configuration

I'm running vim on Arch Linux.

My `vim --version` outpupt is the following:

```
% vim --version                                                                                                                (master=)
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 29 2016 11:28:12)
Included patches: 1-1797
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl/dyn
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +termtruecolor
+channel         +gettext         -mzscheme        +textobjects
+cindent         -hangul_input    +netbeans_intg   +timers
+clientserver    +iconv           +packages        +title
+clipboard       +insert_expand   +path_extra      +toolbar
+cmdline_compl   +job             +perl/dyn        +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```
My `.vimrc` is over there: https://github.com/Marneus68/dotfiles/blob/master/.vimrc

My `go version` is the following:

```
% go version                                                                                                                   (master=)
go version go1.6.2 linux/amd64
```

Thanks in advance for any help you guys can provide me.

**Comment by fatih** [comment]
Hi @Marneus68 

Did you installed `gocode`? Also where do you call it? For example do you call it after the dot of a `fmt.` string?

**Comment by Marneus68** [comment]
I do have `gocode` installed in `$GOPATH/bin`. I do have `$GOPATH/bin` in my path too!

I also forgot to mention that I use fish and have applied all specific configuration mentioned [here](https://github.com/fatih/vim-go/wiki/FAQ-Troubleshooting#im-using-fish-shell-but-have-some-problems-using-vim-go) in my `.vimrc` and `fish.config`.

**Comment by fatih** [comment]
Seems like it's a wrong usage. The error message in case of a `<c-x> <c-o>` usage is `"Pattern not found"` for a Go file. Can you please try it with a minimalistic vimrc and bash? After that use minimalistic vimrc and fish. I'm not sure what the problem here is. Can you just test it with `vim-go` installed, minimal vimrc and bash first please ?

**Comment by Marneus68** [comment]
I'm going to try it out with minimalistic configurations files. Maybe it's something specific to fish. I'll keep you posted if it's something important.

**Comment by Marneus68** [comment]
I don't exactly know how, but I fixed it. Sorry of the inconvenience and thanks for your help and your time on this great project.

**Comment by fatih** [comment]
No worries, great that you fixed it :)

**Comment by motomux** [comment]
Hi,

I get the same issue.

For my case it shows the following text.
`-- ^X mode (^]^D^E^F^I^K^L^N^O^Ps^U^V^Y)`

I tried it with the following minimal vimrc but I still have the issue.

```
" vim-plug
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
Plug 'nsf/gocode', { 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
call plug#end()
```

Versions
Vim: 8.0.2
Go: 1.7.1
Zsh: 5.2
OSX: 10.11.6

Thank you

**Comment by Arion-Dsh** [comment]
@motomux the same issue.
I fixed it with this: gocode close && go get -u github.com/nsf/gocode
maybe you want try that
