### ISSUE TITLE
GoTestCompile not always deleting created test-binary with Neovim

### ISSUE THREAD

**Issue by Limdi** [fatih/vim-go#907]
Hi,
#879 said GoTestCompile removes its created test-binaries which works fine working on go-files in the same directory, I'd love to see this removing of the test-binary incase it got created in another directory too.

### Actual behavior

```
➜  pkg git:(master) ✗ ls storage 
github  github.go  gitlab.go  storage.go  storage_test.go
➜  pkg git:(master) ✗ nvim storage/storage.go
# Running in neovim GoTestCompile
➜  pkg git:(master) ✗ ls storage 
github  github.go  gitlab.go  storage.go  storage_test.go  vim-go-test-compile
```
For me it reproduces nicely for other directories too
```
➜  pkg git:(master) ✗ find . | grep vim-go-test     
./storage/vim-go-test-compile
./mirror/project/vim-go-test-compile
./mirror/vim-go-test-compile
```

### Expected behavior

```
➜  pkg git:(master) ✗ ls storage 
github  github.go  gitlab.go  storage.go  storage_test.go
➜  pkg git:(master) ✗ vim storage/storage.go
# Running in vim :GoTestCompile
➜  pkg git:(master) ✗ ls storage
github  github.go  gitlab.go  storage.go  storage_test.go
```

### Configuration

Add here your current configuration and additional information that might be
useful, such as:

* `vimrc` you used to reproduce
* vim version:
```
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

* vim-go version: latest updated with :PlugUpdate
```
523d5a435d490c8c5ea3d8ed0ecac453e2f33f93
```
* go version
```
go version go1.6.2 linux/amd64
```

**Comment by nightlyone** [comment]
I can reproduce this too:
* Linux (Ubuntu 16.04, codename Xenial) using go 1.6.2 too.
* Vim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)

**Note:**
A simple workaround for me was to use `/dev/null` (or `NUL` on windows) instead of "vim-compile-test" as the compiler target at https://github.com/fatih/vim-go/blob/master/autoload/go/cmd.vim#L194 in order to discard compiler result.

**Comment by fatih** [comment]
Thanks @Limdi for the report. I'm looking into it.

@nightlyone unfortunately `/dev/null/` is not supported by the go tool. We have the same problem for `go build ` as well. I know the problem for this issue. I have a fixed version for Vim already, testing it now for NeoVim.

**Comment by fatih** [comment]
Thanks for the feedback. This issue is now fixed both for Vim and NeoVim. Please pull the latest HEAD of the master branch. Thanks.

**Comment by Limdi** [comment]
Wonderfull, thanks you fatih!

**Comment by 7AC** [comment]
I'm still having this issue with vim 8.0, the latest plugin installed via Vundle and this config which I basically copied from the tutorial:

```
function! s:build_go_files()
  let l:file = expand('%')
  if l:file =~# '^\f\+_test\.go$'
    call go#cmd#Test(0, 1)
  elseif l:file =~# '^\f\+\.go$'
    call go#cmd#Build(0)
  endif
endfunction
au BufWritePost *.go :call <SID>build_go_files()
```

**Comment by oryband** [comment]
Still happenning to me as well.

**Comment by rafael84** [comment]
I'm using **vim 8.0.95** and **vim-go 1.12**. The issue is still happening.

**Comment by rafael84** [comment]
So I think the problem only happens when the current working directory is not the base directory of the test file.

I can easily reproduce the problem by running the following commands:

```
% tree
.
└── mypkg
    └── my_test.go

1 directory, 1 file


% cat mypkg/my_test.go
package mypkg

import "testing"

func TestMy(t *testing.T) {

}


% vim mypkg/my_test.go +GoTestCompile +'sleep 1' +qall


% tree
.
└── mypkg
    ├── my_test.go
    └── vim-go-test-compile

1 directory, 2 files
```

However, check what happens when the current directory is **mypkg**:

```
% tree
.
└── mypkg
    └── my_test.go

1 directory, 1 file


% cd mypkg; vim my_test.go +GoTestCompile +'sleep 1' +qall; cd ..


% tree
.
└── mypkg
    └── my_test.go

1 directory, 1 file
```

**Comment by fatih** [comment]
@rafael84 please pull the latest master. We don't produce a test file anymore.

**Comment by rafael84** [comment]
Awesome, thanks fatih.
